name: Deploy en AWS Lightsail

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar conexi贸n SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configurar y desplegar en AWS Lightsail
        env:
          HOST: ubuntu@34.238.80.206 # Reemplaza con la IP de tu Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@34.238.80.206 << 'EOF'
          
          # Actualizar el sistema e instalar Git
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y git

          # Instalar Node.js y npm
          curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt install -y nodejs

          # Crear y establecer permisos en el directorio del proyecto
          sudo mkdir -p /var/www/react-app
          sudo chown -R $USER:$USER /var/www/react-app
          cd /var/www/react-app

          # Clonar el repositorio o hacer pull si ya existe
          if [ -d ".git" ]; then
              git pull origin main
          else
              git clone https://github.com/ItaloOrganization/ReactMaquinaVirtual.git .
          fi

          # Instalar dependencias y construir la aplicaci贸n
          if [ -f "package.json" ]; then
              npm install
              npm run build
              
              # Instalar 'serve' globalmente para servir el proyecto
              sudo npm install -g serve

              # Servir la aplicaci贸n construida en el puerto 80
              sudo npx serve -s build -l 80 &
          else
              echo "El archivo package.json no se encontr贸 en el repositorio."
              exit 1
          fi

          EOF
