name: Deploy React App en AWS Lightsail

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Conexion SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Despliegue en Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@34.238.80.206 << 'EOF'
          cd /var/www/html
          
          # Clonar o actualizar el repositorio
          if [ -d ".git" ]; then
              git pull origin main
          else
              git clone https://github.com/ItaloOrganization/ReactMaquinaVirtual.git
          fi
          
          # Instalar dependencias y construir la aplicación
          npm install
          npm run build
          
          # Mover los archivos de construcción a la carpeta raíz del servidor
          cp -r build/* /var/www/html
          EOF
